### PR TITLE
Fix installation and remove scripts, put them back in a working state

### PR DESCRIPTION
**Pull request by autra**
This PR is a first attempt at putting diaspora in a working state.

With this, it should remove and install correctly. That being said, a lot of rough edges still remains:

- log location and logrotate should be checked
- no form of integration with yunohost authorization system is done at the moment.
- admin should be created automatically (at the moment, it is still necessary to create an account and follow this)
- mail should be sent with ynh mail server
- implement backup/restore
- implement upgrade
- and generally pass linter
- it's not clear to me what kind of integration do we want with yunohost users. Do we just create an admin ? Do we do more than that (eg allowing yunohost user to automatically log to diaspora)

but at least it's possible to test and play with it a bit.

Thanks!

### CODE REVIEW

**Comment by alexAubin** [comment]
Bump (though I don't know who's supposed to answer .. @Rafi594 ?)

This looks like some meaningful and important work ... and the app appears to be unmaintained (and is flagged as notworking so far)

So maybe we can consider yolomergin if there's no obvious issue, idk ...

**Comment by autra** [comment]
I'd wait a bit, because installing this currently causes cron.daily to send this message every night:

```
/etc/cron.daily/yunohost-certificate-renew:
Timed out when server tried to contact itself through HTTP using public IP address (domain diaspora.trancart.eu with ip 82.64.20.169). You may be experiencing hairpinning issue or the firewall/router ahead of your server is misconfigured.
```
It seems to be a timeout issue, so maybe there is something wrong with my nginx conf. It seems more or less harmless, but it can scare people :-)

**Comment by autra** [comment]
I'll ping you when this is solved.

**Comment by autra** [comment]
ok so I think it's actually a simple timeout issue because I've put a `StopWhenUnneeded=true` in the service configs. As the cron runs in the night, the service is very often shut down and it takes more than 10 seconds to reload. I'll remove this as a quickfix and think about it later.

**Comment by autra** [comment]
>  I've put a `StopWhenUnneeded=true` in the service configs.

no actually, I'm stupid: my backup cron was firing at the same time as anacron jobs, causing a heavy load on my server... Fixed now.

@Rafi594 @alexAubin From my perspective, this is enough to put this app into "working" state.

To give a bit more personal context on this work: I convinced a bunch of people to switch to a free alternative after the recent closing of [famicity](https://www.famicity.com), and they chose diaspora (over friendica and mastodon for the record). 

There is also a non-working docker diaspora app for yunohost, but I think the use of docker is unnecessary here, so that's why I decided to work on this app instead.

Also, this means I'm gonna have to make this work for the next foreseeable future, so I'm offering to maintain this app if you guys want.

Next step: backup and restore scripts.

**Review by Rafi594 — APPROVED** [review]
Thanks for the great work ! It's ok for me to merge it

**Comment by alexAubin** [comment]
Thanks again for you work ! I dunno if the PR is mergeable right now, but to reiterate, considering the app is "notworking" in apps.json right now, imho it's ok to yolomerge anytime. Feel free to ask for help with this on the chat if needed (like accesses or whatever)

**Comment by alexAubin** [comment]
@YunoHost-Apps/apps-group I took the liberty to add @autra  to the diaspora_ynh group

**Comment by autra** [comment]
Just added a commit that correctly removes the yunohost service.

**Pull request merged**
